### ISSUE TITLE
requirements.txt contains null characters

### ISSUE THREAD

**Issue by YounesB-McGill** [jasonjoh/python_tutorial#11]
When cloning this repo, installing requirements from the provided `requirements.txt` fails with the error

```
Traceback (most recent call last):
  File "/home/username/.local/bin/pipenv", line 10, in <module>
    sys.exit(cli())
  [...]
  File "/home/username/.local/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/req/constructors.py", line 207, in install_req_from_line
    looks_like_dir = os.path.isdir(p) and (
  File "/usr/lib/python3.7/genericpath.py", line 42, in isdir
    st = os.stat(s)
ValueError: embedded null byte
```

Interestingly, if I open a text editor I find a null character (`\x00`) between every other character. Deleting them fixes the problem.

I am using Ubuntu 19.10 and Python 3.7.

**Comment by jasonjoh** [comment]
Closing this issue as I'm archiving this sample. We've retired the tutorial that this is based on and we're redirecting to the Microsoft Graph tutorial at https://docs.microsoft.com/graph/tutorials/python. The corresponding GitHub repo is https://github.com/microsoftgraph/msgraph-training-pythondjangoapp.
